import { Legend } from "@/components/Verdict";

export const metadata = { title: "Methodology · Fibrescope" };

export default function Methodology() {
  return (
    <div className="prose">
      <h1>Methodology</h1>
      <p className="muted">What is measured, from where, and what each word on this site means. The source of truth is <code>docs/verdicts.md</code> and <code>docs/research/R4-probe-etiquette.md</code> in the repository; this page restates them.</p>

      <h2 id="why">What the chain cannot tell you</h2>
      <p>Everything about Fibre that a node can answer over RPC is about the <em>moment a blob was published</em>. Nothing on chain describes a validator&rsquo;s Fibre service after that.</p>
      <p><strong>On chain, and queryable from any node:</strong> the host each validator registered in <code>x/valaddr</code> and when it first appeared; every <code>MsgPayForFibre</code> with its promise hash, commitment, blob size, signer and the signature set carried at settlement; and the <code>x/fibre</code> parameters in force. From the signature set you can derive who was proven to hold a shard <em>at upload time</em>, and nothing more.</p>
      <p><strong>Not on chain, at all:</strong> whether an endpoint answers now; whether a validator still serves a shard it signed for; whether its TLS certificate is still endorsed by its consensus key; how fast it responds; whether it pruned before its deadline. There is no serving proof, no challenge protocol and no slashing for not serving. Retention is an obligation the chain records and never checks.</p>
      <p>That is by design, and the Celestia core team has said so directly. Asked in the CIP-51 research thread how a server that signs without storing, or prunes early, would be detected, the answer was that the protocol relies on an honest majority, that only a third of the validator set needs to be honest for the rows to be retrievable, and that beyond that the final layer is social consensus. Asked whether the core team would ship external probing of registered endpoints, the answer was that the community is expected to build the dashboards that periodically check whether the hosts in <code>x/valaddr</code> are reachable and whether validators are serving the data. (<a href="https://forum.celestia.org/t/fibre-shardretention-and-what-happens-when-an-assigned-validator-doesnt-serve/2288" rel="nofollow noopener noreferrer" target="_blank">forum thread</a>)</p>
      <p>Two things follow, and they are why this site is built the way it is.</p>
      <p>First, where there is no enforcement, <strong>a public and checkable record is the enforcement</strong>. That raises the bar on the record rather than lowering it: every figure here has to be reproducible from stored rows anyone can download, every accusation has to be stated in the direction it accuses, and anything this observer cannot distinguish has to be published as undistinguished rather than resolved in either direction. A reputational mechanism built on a number nobody can check is worse than none.</p>
      <p>Second, &ldquo;a third of the set is honest&rdquo; is not a slogan here, it is the figure at the bottom of the overview. The assignment hands out roughly three times the rows needed to rebuild a blob, so any honest third of the voting power holds enough. <strong>Recoverable</strong> &mdash; could this blob still be rebuilt from the rows that actually came back &mdash; is that assumption measured rather than assumed.</p>
      <p>A validator can already watch its own Fibre server: the binary exports OTLP metrics and ships a Grafana dashboard. That answers a different question. A server&rsquo;s own metrics are its own account of itself, from inside its own network: they cannot say whether it is reachable from outside, whether the certificate it presents is one a client will accept, or whether it is doing better or worse than the rest of the set. An indexer of the chain, however good, inherits the limits above: it can show how many blobs were published and who signed, not whether anyone is still serving them.</p>

      <h2 id="promise">The promise being checked</h2>
      <p>When a client publishes a blob to Fibre, the validators sign that they received their assigned rows and the chain records the payment (<code>MsgPayForFibre</code>). Each signing validator then owes serving of its rows to anyone who asks until <code>must_serve_until = creation_timestamp + max(payment_promise_timeout, shard_retention)</code>, using the x/fibre parameters in force when the blob settled. The chain does not observe whether serving continues. This site does, from outside, as an ordinary client.</p>

      <h2 id="probe">One probe</h2>
      <p>A probe is one attempt to fetch one validator's shard for one blob: resolve the registered host (x/valaddr), open TCP, complete a TLS 1.3 handshake, check that the certificate's extension is endorsed by the validator's consensus key (<code>fibre-tlsverify</code>), call <code>DownloadShard</code>, verify every returned row against the blob commitment, and check that the returned row indices are exactly the ones assigned (<code>fibre-assign</code>, a bit-identical reimplementation of celestia-app's assignment, verified across about 890 differential scenarios). Each layer is timed and recorded separately.</p>

      <h2 id="schedule">Schedule</h2>
      <p>For every publication the prober plans four in-window points at 12%, 45%, 72% and 92% of the window, packed toward the deadline where early pruning shows, one grace point 30 s after <code>must_serve_until</code>, and one post point 3.5 min after it where "not found" is the expected answer. An honest server prunes on a one-minute loop with minute-resolution keys, so a shard outlives the deadline by about 1 to 2 minutes; the grace tolerance (2m30s) exists so that lag is never called a fault.</p>

      <h2 id="verdicts">Verdicts</h2>
      <p>Each probe gets exactly one class from the probe outcome, the phase of the window at the actual start time, whether the validator was assigned the shard, and whether the settled promise proves it stored the shard.</p>

      <h2>Who is actually obliged</h2>
      <p>Assignment is the publisher&rsquo;s arithmetic. A validator becomes obliged only once it holds the shard, and the only on-chain evidence of that is a signature from the validator on the settled <code>MsgPayForFibre</code>: a Fibre server writes the shard to its store <em>before</em> it signs. This site verifies those signatures itself against each validator&rsquo;s consensus key rather than trusting the count in the transaction, because the chain&rsquo;s own check runs in the ante handler and is skipped when the block is finalised or when the node has already seen the message, so a settled transaction carries no guarantee that its signature entries are valid.</p>
      <p>A missing signature is <strong>not</strong> evidence that a validator failed to store the shard. The publisher stops collecting signatures the moment it has enough voting power to be safe and keeps delivering to the rest in the background, so a validator can hold a shard whose signature never reached the chain. Absence means <em>unproven</em>, never <em>absent</em>.</p>
      <p>So a probe of an assigned but unattested validator is recorded as <strong>UNATTESTED</strong> whatever happened on the wire, and sits outside the serve rate in both directions. A failure the validator was never proven to owe cannot count against it, and a success it was never proven to owe cannot count for it. The wire outcome is still published, and every page that shows a serve rate also shows how much of the set the rate speaks for.</p>

      <h2 id="quorum">Two thirds, and why most validators are unproven</h2>
      <p>This is the single fact most likely to be misread on this site, so it is stated plainly: <strong>on any given blob, roughly a third of the validator set will have no signature on chain, and that is the protocol working as designed.</strong> It is not a missed duty, it is not downtime, and this site never counts it as either.</p>
      <p>The publisher uploads shards to every bonded validator at once and collects their signatures as they arrive. It stops the moment the signatures it holds represent <strong>two thirds of total voting power</strong> — the same threshold the chain&rsquo;s own check applies when the transaction settles — and submits. Deliveries already in flight to the remaining validators are not cancelled; they simply finish after the transaction is on chain, where nothing records them. Those validators very often do hold the shard. The chain is silent about it, and this site will not fill that silence in either direction.</p>
      <p>Which validators land inside the quorum is a <strong>race, not a list</strong>. The publisher fans every upload out at once, one goroutine per validator, and detaches the moment the collected power crosses the threshold, so membership is upload-completion order. The same validator is inside on one blob and outside on the next.</p>
      <p>How large that quorum is can be bounded. Over the mocha validator set (79 validators, 322,778,683 total voting power) simulated across 20,000 uniformly random arrival orders it holds a <strong>median of 53 of 79</strong> validators; the smallest it can produce is 30, the case where the largest validators all answer first, and that is a bound rather than an expectation.</p>
      <p><strong>Who is in it cannot be bounded that way, and this site does not claim to know.</strong> Completion order is not uniformly random: it depends on the size of the shard, which scales with stake, so a large validator has more bytes to receive; on the network path between that particular publisher and that validator; and on the validator&rsquo;s own write-and-sign latency. This observer measures none of those. So a validator persistently outside the quorum may well be telling you something about itself &mdash; that it is slow, or far from where blobs are published &mdash; and the serve rate, whose population is exactly the validators that answered fast enough, is correspondingly biased toward the ones least likely to be a problem. An earlier version of this page said inclusion was flat across stake: that was a property of the simulation&rsquo;s assumption rather than a measurement, and it is withdrawn.</p>
      <p>This is the main reason each validator&rsquo;s page leads with reachability and certificate validity rather than with the serve rate. Those come from a TLS handshake with every registered endpoint every five minutes whether or not anything was assigned, so their coverage does not depend on a quorum anyone happened to be in, and they carry no selection effect of this kind.</p>
      <p>Counts of unproven obligations are published per blob, never per probe. Each obligation is visited at four schedule points, so a probe count of the same fact reads about four times larger than the fact — and a four-figure number beside an operator&rsquo;s name reads as an accusation where the chain is merely quiet.</p>

      <h2 id="what-this-excludes">What the serve rate leaves out</h2>
      <p>The rate is <code>HEALTHY / (HEALTHY + FAULT)</code> over probes of an assigned shard, in window, where the settled promise proves the validator stored it. Everything else is published under its own name beside the rate, never folded into it:</p>
      <ul>
        <li><strong>UNATTESTED</strong> — the quorum above: nothing on chain proves this validator was ever sent the shard.</li>
        <li><strong>UNREACHABLE</strong> — this site could not complete a conversation with the endpoint. Half of that path is ours.</li>
        <li><strong>NOT_REGISTERED</strong> — no Fibre host in x/valaddr at the time of the probe.</li>
        <li><strong>SHADOWED_SHARD</strong> — the rows verify against the blob commitment but belong to another promise over the same blob; <code>DownloadShard</code> is addressed by commitment alone.</li>
        <li><strong>IDENTITY_EXPIRED</strong> — the certificate carries the right consensus key&rsquo;s endorsement but its signed validity window has lapsed. Endpoint hygiene, not a retention failure.</li>
        <li><strong>NOT_PROBED</strong> and <strong>PROBE_ERROR</strong> — this site&rsquo;s own gaps, never a zero.</li>
      </ul>
      <p><strong>Verdict coverage</strong>, shown next to every rate, is how much of that population produced a verdict at all.</p>
      <p>One thing this site cannot see and an operator should know about: a Fibre server derives its storage budget from its validator&rsquo;s stake, and a validator outside the active set gets none. A server whose budget is zero or exhausted may legitimately not be holding a shard. Where it never signed, that is <code>UNATTESTED</code> and costs it nothing. Where it signed and later dropped the shard under budget pressure, the protocol calls that a retention failure and so does this site &mdash; correctly, but without being able to say why it happened, because the budget is derived inside the server and never published. If a fault count here does not match what you see, that is one of the first places to look.</p>
      <Legend />
      <p><strong>FAULT is the only class that counts against a validator.</strong> It means: while the promise held, the validator answered not found, was unreachable at any layer, presented a certificate its consensus key did not endorse, or returned wrong, partial or unverifiable rows.</p>

      <h2 id="rates">Rates</h2>
      <ul>
        <li><strong>Serve rate</strong> = HEALTHY / (HEALTHY + FAULT), over probes of an assigned shard while the validator was under obligation and the settled promise proves it held that shard. A <strong>fault</strong> means both halves of one sentence: this site reached the validator, and it failed to hand over a shard the chain proves it stored. Everything short of that is listed next to the rate under its own name and never folded in.</li>
        <li>The grace phase is outside the rate. A grace probe can only ever add HEALTHY, because not-found and unreachability there are tolerated by design, so counting grace gave a validator that prunes promptly a lower rate than one that over-retains with identical behaviour. Grace probes are still recorded and still shown.</li>
        <li><strong>Unreachable</strong> is its own class, not a fault. From one location, an endpoint that will not talk to us is not distinguishable from a route, firewall or peering problem on our own path, and we will not publish an accusation the evidence does not support. The same goes for a validator with no registered Fibre host (jailing and unbonding drop it from the bonded list while the chain keeps the entry), for rows that verify against the blob commitment but belong to another promise over the same blob, and for a certificate signed by the right key whose validity window has lapsed.</li>
        <li><strong>Verdict coverage</strong> tells you how much of that population produced a verdict at all. A high rate over low coverage is a statement about a handful of probes.</li>
        <li>Rates are counted a second time <strong>per obligation</strong>: one observation per validator per blob, kept when no probe of it faulted. The schedule visits the same pair four times in window and every bonded validator is assigned every blob, so the probes inside one obligation are near copies of each other — one lapsed certificate makes four fault rows for one event. Any confidence interval is drawn around the obligation count, and stated as an upper bound on the fault rate, because that is the direction an accusation is made in.</li>
        <li>Below twenty rated observations no percentage is printed. The counts are shown instead and the validator is not ranked among the worst: one unlucky probe is not a measurement.</li>
        <li><strong>Status</strong> = the latest handshake or probe of the endpoint: up if TCP and TLS completed and the certificate was endorsed. A handshake is attempted with every registered endpoint every 5 minutes without downloading, so the column stays live on days a validator has nothing assigned.</li>
        <li><strong>Uptime</strong> = handshakes completed over handshakes attempted, over the whole window: 288 a day per registered endpoint. It is the one figure here whose coverage does not depend on being assigned or attested anything, which is why the validator table and each validator&rsquo;s page lead with it. No confidence bound is drawn around it: half of every path it measures is this site&rsquo;s own, and an interval would dress a statement about a route as a statement about an operator.</li>
        <li><strong>Endorsed</strong> = of the heartbeats that got far enough to see a certificate, how many carried an extension signed by that validator&rsquo;s consensus key. The denominator excludes heartbeats that never completed TLS, because an endpoint that was down presented nothing to judge and counting it would report one outage twice.</li>
        <li><strong>TLS identity</strong> = the consensus-key check on the latest handshake: verified, mismatch, no TLS, or unreachable.</li>
        <li><strong>Serve rate by point</strong> is published per validator as well as network-wide. The four in-window points sit at different fractions of the retention window, so a validator that serves at the first point and not the last has pruned before it was allowed to, which is a different finding — and a different fix — from one that is poor throughout. The pooled rate cannot tell them apart.</li>
        <li><strong>Reconstructable</strong> (per blob) = at the latest in-window probe point, the union of row indices of validators whose probe was HEALTHY is at least <code>OriginalRows</code> (4096 of 16384 for blob version 0). &ldquo;Degraded&rdquo; means enough rows but not every validator that was proven to owe the blob answered; a validator with no proof of storage cannot demote the verdict by staying quiet. A row that came back counts toward reconstruction either way, because the data was there: attestation decides blame, never availability. Grace and post points are never used for this verdict.</li>
        <li><strong>Throughput</strong> = rows handed over per second, from dial to rows verified against the commitment, over the probes that came back HEALTHY. Fibre exists to be fast, and every other figure on this site would call a validator that serves everything in twenty seconds perfect. It is stated as rows per second rather than milliseconds because assignments run from the 148-row floor to the 4,096-row ceiling: a validator carrying eight times another&rsquo;s rows takes longer for the same quality of service, so a duration column would sort the busiest validators to the bottom and name the wrong ones. The median and 95th percentile of the whole probe are printed alongside, because those are the numbers an operator recognises from their own logs. <strong>No threshold is attached to any of it.</strong> This site watches from one place, so part of every millisecond is its own path, and calling a validator &ldquo;slow&rdquo; from one vantage would be the same mistake as calling one unreachable from one vantage. Failed probes are excluded: how long a failure took is not a service time.</li>
        <li>Every rate shows its numerator and denominator, and every serve rate carries a Wilson 95% <strong>upper bound on the fault rate</strong>, drawn around the obligation count rather than the probe count, because 3 of 3 is not 3000 of 3000. It is stated in that direction because that is the direction an accusation is made in.</li>
      </ul>

      <h2 id="gaps">Gaps</h2>
      <p>NOT_PROBED and PROBE_ERROR rows are the observer's own gaps: the slot elapsed while the observer was down, the probe policy sampled the blob out, or the probe itself failed. They are counted and shown, and never enter a rate. Observer run spans are recorded (<code>/v1/runs</code>), so downtime is rendered as a gap, not as zero.</p>

      <h2 id="sampling">Load policy and sampling</h2>
      <p>A probe transfers the validator's whole shard; there is no partial-row download in the protocol. To stay a small fraction of a validator's capacity, the prober enforces per-validator caps (requests per minute, bytes per hour and per day, scaled by assigned rows) and global caps. When the projected load for the next hour would exceed a cap, publications are sampled at probability <em>p</em> = cap / projected. The sample is deterministic and unpredictable: a blob is probed iff <code>H(promise_hash || day_secret) &lt; p · 2^64</code>, where <code>day_secret = HMAC(master, date)</code>. Every row this site stores, probed or sampled out, carries the probability it was decided at and a commitment to that day&rsquo;s secret (SHA-256 of the secret). Those commitments are published at <code>/v1/sampling</code>. When a day&rsquo;s secret is revealed, anyone can recompute the draw for every <code>MsgPayForFibre</code> settled that day and check which publications this site should have probed against which ones it did, from <code>/v1/probes</code>. The secrets are not published yet, and the endpoint says so. A sampled-in blob gets its whole schedule; a sampled-out blob is recorded NOT_PROBED with the reason and <em>p</em>. Backoff only ever removes the download step after repeated transport failures; it never adds requests.</p>

      <h2 id="vantage">Vantage</h2>
      <p>All measurements on this site come from the vantage named in the footer. A failed probe means this vantage could not fetch the rows at that time; it is not proof the validator is down. A successful probe is not proof of availability from elsewhere. Adding vantages multiplies load on validators, so a second one comes after the policy above has been published.</p>

      <h2 id="not">What this site does not do</h2>
      <ul>
        <li>It is not an availability proof and produces no slashing evidence; Fibre has no on-chain penalty for not serving.</li>
        <li>It does not extrapolate: rows not probed are not counted as served.</li>
        <li>It does not rank validators by anything other than the stored probe rows you can download from the API.</li>
      </ul>
    </div>
  );
}
