import { Legend } from "@/components/Verdict";
import { DISPUTE_URL, SOURCE_URL } from "@/lib/site";
import ProtocolParams from "@/components/ProtocolParams";

// The rules version, as verdict.MethodologyVersion in the Go code and
// methodology_version in /v1/meta and every export manifest. Bumped in the
// same change as any rule that can move a figure.
const METHODOLOGY_VERSION = "2026-09-25";

export const metadata = { title: "Methodology · Tensile · Celestia Fibre" };

export default function Methodology() {
  return (
    <div className="prose">
      <h1>Methodology</h1>
      <p className="muted">What is measured, from where, and what each word on this site means. The source of truth is <code>docs/verdicts.md</code> and <code>docs/research/R4-probe-etiquette.md</code> in the repository; this page restates them.</p>
      <p className="muted">Methodology version <b>{METHODOLOGY_VERSION}</b>, published with every figure as <code>methodology_version</code> in <code>/api/v1/meta</code> and in every daily export&rsquo;s manifest. <a href={`${SOURCE_URL}/commits/main/web/src/app/methodology/page.tsx`} rel="noopener noreferrer" target="_blank">Change history</a>.</p>

      <h2 id="why">What the chain cannot tell you</h2>
      <p>Everything about Fibre that a node can answer over RPC is about the <em>moment a blob was published</em>. Nothing on chain describes a validator&rsquo;s Fibre service after that.</p>
      <p><strong>On chain, and queryable from any node:</strong> the host each validator registered in <code>x/valaddr</code> and when it first appeared; every <code>MsgPayForFibre</code> with its promise hash, commitment, blob size, signer and the signature set carried at settlement; and the <code>x/fibre</code> parameters in force. From the signature set you can derive who was proven to hold a shard <em>at upload time</em>, and nothing more.</p>
      <p><strong>Not on chain, at all:</strong> whether an endpoint answers now; whether a validator still serves a shard it signed for; whether its TLS certificate is still endorsed by its consensus key; how fast it responds; whether it pruned before its deadline. There is no serving proof, no challenge protocol and no slashing for not serving. Retention is an obligation the chain records and never checks.</p>
      <p>That is by design, and the Celestia core team has said so directly. Asked in the CIP-51 research thread how a server that signs without storing, or prunes early, would be detected, the answer was that the protocol relies on an honest majority, that only a third of the validator set needs to be honest for the rows to be retrievable, and that beyond that the final layer is social consensus. Asked whether the core team would ship external probing of registered endpoints, the answer was that the community is expected to build the dashboards that periodically check whether the hosts in <code>x/valaddr</code> are reachable and whether validators are serving the data. (<a href="https://forum.celestia.org/t/fibre-shardretention-and-what-happens-when-an-assigned-validator-doesnt-serve/2288" rel="nofollow noopener noreferrer" target="_blank">forum thread</a>)</p>
      <p>Two things follow, and they are why this site is built the way it is.</p>
      <p>First, where there is no enforcement, <strong>a public and checkable record is the enforcement</strong>. That raises the bar on the record rather than lowering it: every figure here has to be reproducible from stored rows anyone can download, every accusation has to be stated in the direction it accuses, and anything this observer cannot distinguish has to be published as undistinguished rather than resolved in either direction. A reputational mechanism built on a number nobody can check is worse than none.</p>
      <p>Concretely: every record file is published as a daily export with digests (<code>/api/v1/exports</code>); every process records the build and flags it ran under (<code>/api/v1/runs</code>); the API answers any window as of any past moment (<code>?as_of=</code>); and <code>sentinel-recompute</code> re-derives every row&rsquo;s verdict and every obligation figure from an export, in a second implementation of the rules kept apart from the one the site runs, and prints what differs.</p>
      <p>Second, &ldquo;a third of the set is honest&rdquo; is not a slogan here, it is the <em>Blob availability</em> figure on the overview. The assignment hands out roughly three times the rows needed to rebuild a blob, so any honest third of the voting power holds enough. <strong>Rebuildable</strong> &mdash; could this blob still be rebuilt from the rows that actually came back at the latest complete probe point &mdash; is that assumption measured rather than assumed; <strong>fully served</strong> is the stricter reading, where every validator proven to hold a shard served it. Both are observations of rows, never an actual rebuild.</p>
      <p>A validator can already watch its own Fibre server: the binary exports OTLP metrics and ships a Grafana dashboard. That answers a different question. A server&rsquo;s own metrics are its own account of itself, from inside its own network: they cannot say whether it is reachable from outside, whether the certificate it presents is one a client will accept, or whether it is doing better or worse than the rest of the set. An indexer of the chain, however good, inherits the limits above: it can show how many blobs were published and who signed, not whether anyone is still serving them.</p>

      <h2 id="promise">The promise being checked</h2>
      <p>When a client publishes a blob to Fibre, the validators sign that they received their assigned rows and the chain records the payment (<code>MsgPayForFibre</code>). Each signing validator then owes serving of its rows to anyone who asks until <code>must_serve_until = creation_timestamp + max(payment_promise_timeout, shard_retention)</code>, using the x/fibre parameters in force when the blob settled. The chain does not observe whether serving continues. This site does, from outside, as an ordinary client.</p>

      <h2 id="params">Protocol parameters</h2>
      <p>The numbers the deadline above is computed from, as this site holds them. The x/fibre parameters are the chain&rsquo;s: read from state at the height the record begins, then updated from every <code>EventUpdateFibreParams</code>, each dated by its block. The protocol constants are compiled into the celestia-app build this site pins and no node or Fibre server exposes them, so they are read from that code and the commit is named. Both are served at <code>/api/v1/params</code>; nothing below is typed into this page.</p>
      <ProtocolParams />

      <h2 id="probe">One probe</h2>
      <p>A probe is one attempt to fetch one validator's shard for one blob: resolve the registered host (x/valaddr), open TCP, complete a TLS 1.3 handshake, check that the certificate's extension is endorsed by the validator's consensus key (<code>fibre-tlsverify</code>), call <code>DownloadShard</code>, verify every returned row against the blob commitment, and check that the returned row indices are exactly the ones assigned (<code>fibre-assign</code>, a bit-identical reimplementation of celestia-app's assignment, verified across about 890 differential scenarios). Each layer is timed and recorded separately.</p>

      <h2 id="schedule">Schedule</h2>
      <p>For every publication the prober plans four in-window points at 12%, 45%, 72% and 92% of the window, packed toward the deadline where early pruning shows, one grace point 30 s after <code>must_serve_until</code>, and one post point 3.5 min after it where &ldquo;not found&rdquo; is the expected answer. An honest server prunes on a one-minute loop with minute-resolution keys, so a shard outlives the deadline by anything up to two minutes (the prune key is the deadline truncated to the minute, and the loop runs once a minute); the grace tolerance (2m30s) exists so that lag is never called a fault.</p>
      <p>The last of those four is also held to an absolute margin: whatever the fraction works out to, it is moved forward to sit no more than 2m30s before <code>must_serve_until</code>. A fraction alone does not survive a change of scale. On a ten-minute window 92% is 48 seconds out; on a four-hour retention it is nineteen minutes out, and since a missing shard at the grace point is tolerated by construction, a validator that pruned inside those nineteen minutes would have served every probe it was given. The margin cannot usefully be tighter than the chain&rsquo;s own prune granularity, which is what sets it: below a minute or two, an early reading would be accusing an operator of the clock.</p>

      <h2 id="verdicts">Verdicts</h2>
      <p>Each probe gets exactly one class from the probe outcome, the phase of the window at the actual start time, whether the validator was assigned the shard, and whether the settled promise proves it stored the shard.</p>
      <p><strong>What a FAULT claims, exactly.</strong> That this site reached the validator and it did not hand over a shard the chain records it as obliged to hold, at a moment inside that obligation. Not more. The chain calls the parameter behind that obligation a <em>minimum local retention</em> &mdash; upstream&rsquo;s own words are &ldquo;the minimum local duration validators keep uploaded shards&rdquo; and &ldquo;the on-chain local retention floor for uploaded shards&rdquo; &mdash; and it neither checks it nor penalises missing it. So a fault here is an observation with a timestamp and a promise hash, not a finding of intent and not evidence for a penalty that does not exist.</p>
      <p><strong>One thing a fault cannot rule out: a power cut.</strong> The Fibre server writes the shard file first and then commits the metadata that makes it discoverable &mdash; the promise record, the <code>/shard/</code> marker, the prune index &mdash; in one pebble batch with <code>NoSync</code>, which hands the write to the operating system without waiting for it to reach the disk. A power loss in between leaves the shard on disk with nothing pointing at it, and the server answers <code>NotFound</code> for data it still physically holds; upstream&rsquo;s own code names that case. From outside it is the same wire answer, the same row and the same fault as an early prune. The shape that tells them apart is in the record rather than in any single row: a machine event puts a validator&rsquo;s faults at one moment across many promises, a retention policy does not. If that is what happened to you, the rows carry the times and the promise hashes, and the <a href={DISPUTE_URL} rel="noopener noreferrer" target="_blank">dispute route</a> puts the correction on the record beside the original.</p>

      <h2>Who is actually obliged</h2>
      <p>Assignment is the publisher&rsquo;s arithmetic. A validator becomes obliged only once it holds the shard, and the only on-chain evidence of that is a signature from the validator on the settled <code>MsgPayForFibre</code>: a Fibre server writes the shard to its store <em>before</em> it signs. This site verifies every signature itself against each validator&rsquo;s consensus key rather than trusting the entries in the transaction. Honest validators check the signatures in <code>CheckTx</code> and <code>ProcessProposal</code>, but the check stops at the quorum: <code>validateValidatorSignatures</code> in <code>x/fibre</code> walks the entries in validator-set order and returns as soon as the ones verified so far carry two thirds of the stake. Entries after that point are never verified by any node, so a settled transaction proves that a quorum signed, not that every signature entry in it is valid.</p>
      <p>A missing signature is <strong>not</strong> evidence that a validator failed to store the shard. The publisher stops collecting signatures the moment it has enough voting power to be safe and keeps delivering to the rest in the background, so a validator can hold a shard whose signature never reached the chain. Absence means <em>unproven</em>, never <em>absent</em>.</p>
      <p>So a probe of an assigned but unattested validator is recorded as <strong>UNATTESTED</strong> whatever happened on the wire, and sits outside the serve rate in both directions. A failure the validator was never proven to owe cannot count against it, and a success it was never proven to owe cannot count for it. The wire outcome is still published, and every page that shows a serve rate also shows how much of the set the rate speaks for.</p>

      <h2 id="quorum">Two thirds, and why most validators are unproven</h2>
      <p>This is the single fact most likely to be misread on this site, so it is stated plainly: <strong>on any given blob, roughly a third of the validator set will have no signature on chain, and that is the protocol working as designed.</strong> It is not a missed duty, it is not downtime, and this site never counts it as either.</p>
      <p>The publisher uploads shards to every bonded validator at once and collects their signatures as they arrive. It stops the moment the signatures it holds represent <strong>two thirds of total voting power</strong> — the same threshold the chain&rsquo;s own check applies when the transaction settles — and submits. Deliveries already in flight to the remaining validators are not cancelled; they simply finish after the transaction is on chain, where nothing records them. Those validators very often do hold the shard. The chain is silent about it, and this site will not fill that silence in either direction.</p>
      <p>Which validators land inside the quorum is a <strong>race, not a list</strong>. The publisher fans every upload out at once, one goroutine per validator, and detaches the moment the collected power crosses the threshold, so membership is upload-completion order. The same validator is inside on one blob and outside on the next.</p>
      <p>How large that quorum is can be bounded. Over the mocha validator set (79 validators, 322,778,683 total voting power) simulated across 20,000 uniformly random arrival orders it holds a <strong>median of 53 of 79</strong> validators; the smallest it can produce is 30, the case where the largest validators all answer first, and that is a bound rather than an expectation.</p>
      <p><strong>Who is in it cannot be bounded that way, and this site does not claim to know.</strong> Completion order is not uniformly random: it depends on the size of the shard, which scales with stake, so a large validator has more bytes to receive; on the network path between that particular publisher and that validator; and on the validator&rsquo;s own write-and-sign latency. This observer measures none of those. So a validator persistently outside the quorum may well be telling you something about itself &mdash; that it is slow, or far from where blobs are published &mdash; and the serve rate&rsquo;s population is exactly the validators that answered fast enough. Whether that makes the rate read better or worse than the network&rsquo;s true retention, this site does not know: it would take a measurement of upload speed against retention, and this site measures only the second. The likelier of the two is that it flatters. It is not corrected in either direction, and the size of what is left out is published beside it. An earlier version of this page said inclusion was flat across stake: that was a property of the simulation&rsquo;s assumption rather than a measurement, and it is withdrawn.</p>
      <p>This is the main reason each validator&rsquo;s page leads with reachability and certificate validity rather than with the serve rate. Those come from a TLS handshake with every registered endpoint every five minutes whether or not anything was assigned, so their coverage does not depend on a quorum anyone happened to be in, and they carry no selection effect of this kind.</p>
      <p>Counts of unproven obligations are published per blob, never per probe. Each obligation is visited at four schedule points, so a probe count of the same fact reads about four times larger than the fact — and a four-figure number beside an operator&rsquo;s name reads as an accusation where the chain is merely quiet.</p>

      <h2 id="signing">Signing participation</h2>
      <p><strong>Signed</strong> is, for one validator over the period, the settled promises carrying its verified signature over the settled promises that assigned it rows &mdash; every promise whose validator set at the promise height included it, host or no host, since the minimum-rows floor gives every member rows. Promises from before this site verified signatures sit on neither side; none assigned is a dash, and under twenty the figure is shown but not ranked. The Blobs page shows the other side: each promise&rsquo;s signed share of total voting power, against the chain&rsquo;s quorum of <code>floor(total &times; 2 / 3)</code>. Neither measures duty. The publisher stops at the quorum, so an unsigned promise is unproven, never a fault.</p>

      <h2 id="what-this-excludes">What the serve rate leaves out</h2>
      <p>The rate is <code>HEALTHY / (HEALTHY + FAULT)</code> over probes of an assigned shard, in window, where the settled promise proves the validator stored it. Everything else is published under its own name beside the rate, never folded into it:</p>
      <ul>
        <li><strong>UNATTESTED</strong> — the quorum above: nothing on chain proves this validator was ever sent the shard.</li>
        <li><strong>UNREACHABLE</strong> — this site could not complete a conversation with the endpoint. Half of that path is ours.</li>
        <li><strong>NOT_REGISTERED</strong> — no Fibre host in x/valaddr at the time of the probe.</li>
        <li><strong>SHADOWED_SHARD</strong> — the rows verify against the blob commitment and are exactly the set another settled promise over the same blob assigns to this validator; <code>DownloadShard</code> is addressed by commitment alone, and the Fibre store keeps every promise&rsquo;s shard side by side and serves the first one in promise-hash order, so that promise answers in this one&rsquo;s place. The row records which promise. Because the order is by hash and not by time, a promise uploaded before the probe and settled after it can be the one that answered, so genuine rows that match no promise the observer has scanned get no verdict at the probe: the row is filed as an observer error with the reason, and the collector draws the verdict once the scanner has read past the probe time plus the payment-promise timeout, when every promise that could have answered is on record &mdash; shadowed if one of them assigns exactly those rows, <strong>unmatched genuine rows</strong> if none does (held out of the rate and counted beside it: a shard uploaded for a promise that never settled is on disk until its prune and never on chain, so a validator can answer with it honestly and no fault is supported), and no verdict at all if a block the scanner could not read falls inside that interval. The row keeps the verdict it was stamped with beside the amended one, and the amendment is part of the record (<code>amendments.jsonl</code>).</li>
        <li><strong>IDENTITY_EXPIRED</strong> — the certificate carries the right consensus key&rsquo;s endorsement but its signed validity window has lapsed. Endpoint hygiene, not a retention failure.</li>
        <li><strong>IDENTITY_MISMATCH</strong> — the certificate is not endorsed by this validator&rsquo;s consensus key. An unusable endpoint, shown as its status (bad certificate); it proves nothing about any shard.</li>
        <li><strong>SERVER_ERROR</strong> — the endpoint answered with an application error instead of the shard. It did not say it lacks the shard, and from one probe a hiccup and a loss look the same.</li>
        <li><strong>THROTTLED</strong> — the endpoint refused the download with a rate limit. That says nothing about the shard. The prober backs off from a validator that says so: after three consecutive transport failures or rate limits it skips the download step, and only the download step, for the next twenty minutes; the handshake still runs and the row is still written, as <em>not probed</em>. The count of rate limits is published per validator, beside the rate, in the table and the API.</li>
        <li><strong>NOT_PROBED</strong> and <strong>PROBE_ERROR</strong> — this site&rsquo;s own gaps, never a zero.</li>
        <li><strong>RETENTION_UNVERIFIED</strong> — Fibre&rsquo;s parameters can change without the chain emitting an event, and how long a shard had to be kept is computed from those parameters. This site re-reads them from chain state every sixty blocks; when a read disagrees with the event history, a change landed somewhere in the range since the last read, and it closes that range by reading the parameters at <em>every</em> height in it. While a range stays open — the node cannot answer for those heights — this site cannot say when the obligation ended for the blobs uploaded inside it, so it publishes no verdict for them: not the failure, and not the credit either. Withholding only the failures would raise the rate on a deadline it cannot vouch for. The ranges are published, and the verdicts return, recomputed, once a range has been read. A recomputed deadline can only be earlier than the recorded one, never later, so a correction can withdraw a fault and never create one.</li>
      </ul>
      <p><strong>Verdict coverage</strong>, published with every rate in the API, is how much of that population produced a verdict at all.</p>
      <p>One thing this site cannot see and an operator should know about: a Fibre server derives its storage budget from its validator&rsquo;s stake; a server that starts outside the active set refuses to start, and one that leaves it keeps the last budget it derived. When the budget is full the server <em>rejects the upload</em> (<code>ResourceExhausted</code>) rather than dropping shards it already holds, so a budget problem shows up here as <code>UNATTESTED</code> &mdash; no signature, no obligation, nothing counted against the validator &mdash; and never as a fault. The server does not evict a shard before its prune time.</p>
      <Legend />
      <p><strong>FAULT is the only class that counts against a validator.</strong> It means one of two things, for a shard the validator signed for, from an endpoint whose certificate its consensus key endorsed: it said it has no shard of this blob at all while the promise held, or it returned bytes that do not verify against the blob commitment. Genuine rows of the blob that are not this promise&rsquo;s assignment are never a fault: the store serves whichever promise&rsquo;s shard sorts first by hash, including one whose promise never settled, so the validator may be answering honestly; such rows are shown beside the rate under their own name. Anyone who repeats the probe gets the same answer. Being unreachable, answering with a server error, refusing with a rate limit, or presenting a wrong certificate are each their own class and never a fault. One margin is deliberate: a not-found answer that arrives within thirty seconds of the deadline is tolerated rather than faulted, because the server prunes on its own clock and the observer&rsquo;s need not agree with it to the second.</p>

      <h2 id="rates">Rates</h2>
      <ul>
        <li><strong>Serve rate</strong>, the headline on every page, is counted <strong>per obligation</strong>: one observation per validator per shard the settled promise proves it held, judged by the last probe of it inside the retention window. <strong>Kept</strong> means that probe came back with the shard, no probe of it was a fault, and at least one of the probes that came back with the shard was taken in the <strong>last quarter of the retention window</strong> &mdash; a shard that was there a minute after settlement says nothing about the hours the promise actually covers; <strong>broken</strong> means any probe of it was a fault. The rate is kept over kept plus broken. Two things sit beside it and never inside it: an obligation that was served early and then produced no reading at the end of its window (<em>end unobserved</em>), and an obligation <strong>never observed serving</strong> &mdash; no probe of it came back with the shard, and none came back with a fault. The latter is split by what the probes did see: the endpoint completed a TLS handshake and still handed nothing over (an error, a rate limit, a certificate no client would accept); it never completed a handshake; or this site never attempted the download (backoff, a load cap, a slot that elapsed). None of these is a fault, and a validator that answers every download with an error is not marked clean by it either: it is marked unobserved, in its own count, next to the rate.</li>
        <li>The last probe decides, not any probe, because the profile this observer exists to notice is a server that serves at the first probe and has pruned by the last. &ldquo;Kept when no probe faulted&rdquo; would have called that kept. The same rule judges whether a blob is reconstructable.</li>
        <li>The <strong>per-probe rate</strong> = HEALTHY / (HEALTHY + FAULT) over probes of an assigned, proven shard while the validator was under obligation, is still published in the API and on each validator&rsquo;s page. A <strong>fault</strong> means both halves of one sentence: this site reached the validator, and it failed to hand over a shard the chain proves it stored. Everything short of that is listed next to the rate under its own name and never folded in.</li>
        <li>The grace phase is outside the rate. A grace probe can only ever add HEALTHY, because not-found and unreachability there are tolerated by design, so counting grace gave a validator that prunes promptly a lower rate than one that over-retains with identical behaviour. Grace probes are still recorded and still shown.</li>
        <li><strong>Every rate is a ratio of sums</strong>: the counts are added up first and divided once, over validators, days and probe points alike. An average of per-day or per-validator rates is never published, because it gives a day with two obligations the same weight as a day with two thousand.</li>
        <li><strong>Refusals while a blob is uploading are expected.</strong> A Fibre server takes 16 concurrent connections by default, and an upload can use all of them; upstream&rsquo;s own configuration notes tell operators to raise <code>max_connections</code> to keep slots free for downloads during uploads (<code>fibre/server_config.go</code>). A probe turned away in that moment is recorded as <em>unreachable</em> (no connection) or <em>rate limited</em> (the server answered <code>ResourceExhausted</code>), never as a fault, and the next probe point asks again.</li>
        <li><strong>Flaky before unreachable.</strong> An endpoint counts as unreachable only after two failed checks in a row. A single failure after a success shows as <em>flaky</em> and still counts as reachable, in the table and in the readiness figure: one timeout on a 10-second TLS deadline is not an outage.</li>
        <li><strong>Unreachable</strong> is its own class, not a fault. From one location, an endpoint that will not talk to us is not distinguishable from a route, firewall or peering problem on our own path, and we will not publish an accusation the evidence does not support. The same goes for a validator with no registered Fibre host (jailing and unbonding drop it from the bonded list; the chain keeps the entry until the validator leaves staking state or has been jailed and unbonded for a week past its unbonding time), for rows that verify against the blob commitment but belong to another promise over the same blob, and for a certificate signed by the right key whose validity window has lapsed. A validator that re-registers during a window is judged at the host clients are sent to now; the row keeps the host the upload went to (read from the chain&rsquo;s own registration events, not from a state query), and when the new host does not serve, the old one is asked as evidence, so a fault after a move says whether the data was left behind or lost.</li>
        <li><strong>Verdict coverage</strong> tells you how much of that population produced a verdict at all. A high rate over low coverage is a statement about a handful of probes.</li>
        <li>Why per obligation: the schedule visits the same validator and shard four times in window and every bonded validator is assigned every blob, so the probes inside one obligation are near copies of each other &mdash; one lapsed certificate makes four fault rows for one event. Any confidence interval is drawn around the obligation count, never the probe count, and stated as an upper bound on the fault rate, because that is the direction an accusation is made in.</li>
        <li>Which obligations: only those the settled promise <em>proves</em>, by a signature verified against the validator&rsquo;s consensus key. A record from before this site verified signatures is not evidence either way and is outside the count. An obligation belongs to a window by its blob&rsquo;s settlement time, so it is judged whole or not at all; one whose retention window has not ended is <em>pending</em> and in no rate.</li>
        <li>How long the rows are kept: raw probe rows for 90 days, the raw JSON behind them for 30. Fourteen days after a day ends, while its rows are all still there, the day is rolled up per validator with the same rules, and only a rolled day is ever pruned. Past the first prune the <em>all</em> window is the rollup plus the raw rows and says so (&ldquo;rolled up after 90 days&rdquo;); the shorter windows never touch it; latency, by-point, attestation and throughput figures cover the raw rows only. The daily export is never pruned.</li>
        <li><strong>Points this site does not trust itself at.</strong> The working assumption is that validators fail independently and one observer&rsquo;s network does not; it is an assumption, not a measurement, and on a day when many endpoints really are down at once it errs toward publishing nothing. At any probe point where at least half of the validators probed, and at least three, were unreachable at once, every probe at that point is left out of every rate, bucket and fault count, and the point is listed on the overview with its share and a link to its rows. The same exclusion applies when half the set faulted at once. That point is listed the same way, and what can be said about it is limited: the assignment pin is checked separately (below), and a params-uncertainty range on record withholds its rows before they can be faults, so the observer errors this site can check for are ruled out; the ones it cannot check for are not, and the point is given no cause. The thresholds are published with the figures. &ldquo;Probed&rdquo; counts only the validators this site got a reachability answer from, because those are the only ones that could have been in the count on the other side of the fraction: a slot that elapsed, a validator with no reachable Fibre host, and one whose assignment carries no signature on the settled promise are all left out of both. That last case is about a third of a typical point, and counting it would have held this check below its threshold through an outage it exists to catch. After a chain upgrade past the celestia-app version this site&rsquo;s assignment is pinned to, the prober records every probe as an observer error rather than a verdict until it is re-pinned.</li>
        <li><strong>Provisional faults.</strong> A fault younger than 30 minutes is shown as <em>Broken · provisional</em>. Two things can still take it back automatically: the rest of its probe point arriving (the prober may run a slot up to 5% of the window late, twelve minutes on a four-hour window, and a point where half the set failed together is left out of everything), and an <code>x/fibre</code> params change that arrived without an event, which the scanner notices within 60 blocks and whose publications are then withheld. Thirty minutes is twice the longest of those. A provisional fault is <strong>counted</strong> in the broken figure and the rate like any other: holding back only the fresh faults would raise a validator&rsquo;s rate while it was failing, which is the one-sided withholding this site refuses everywhere else, and holding back everything decided in the last half hour would just make every figure half an hour older. The badge says which part of the number can still move and until when (<code>provisional_faults.until</code> in the API).</li>
        <li><strong>Every verdict carries its evidence.</strong> A probe row records the row indices returned and a digest of their bytes, the gRPC status code, the promise whose shard answered instead when one did, the certificate&rsquo;s digest, the clock offset, the sampling decision, and the observer build and chain app version the verdict was made under. Anyone with the rows can re-run the classification and check every figure on this site against it.</li>
        <li><strong>Service rate</strong> is always printed with the counts behind it (<code>100% · 9/9</code>), so a small sample shows its own size. Below twenty assessed obligations the validator is not ranked by it in either direction: one unlucky probe is not a measurement. A dash means nothing has been assessed yet (results still pending or inconclusive) or nothing was owed in the period.</li>
        <li><strong>Endpoint now</strong> is liveness only, and the chain&rsquo;s own words come first: <em>jailed</em> or <em>not bonded</em> (out of the bonded provider list, so no handshake is attempted while it is out), <em>no endpoint</em> (nothing registered in x/valaddr). Otherwise the newest handshake or probe of the endpoint: <em>reachable</em> if TCP and TLS completed and the certificate was endorsed, else <em>unreachable</em>, <em>wrong certificate</em>, <em>certificate expired</em> or <em>no TLS</em>. A fault never appears here: it has its own column, and a validator that faulted once yesterday and is reachable today is reachable. A handshake is attempted with every registered endpoint every 5 minutes without downloading, so the column stays live on days a validator has nothing assigned.</li>
        <li><strong>Reachability</strong> = handshakes completed over handshakes attempted, over the whole window: 288 a day per endpoint, counted from the day it entered the bonded provider list. It is the one figure here whose coverage does not depend on being assigned or attested anything, which is why each validator&rsquo;s page shows it beside the service rate. It is not signing uptime: a validator can sign every block with its Fibre endpoint down, and the reverse. Whether the certificate presented was the right one is not in it either; that is <em>Endorsed</em>. No confidence bound is drawn around it: half of every path it measures is this site&rsquo;s own, and an interval would dress a statement about a route as a statement about an operator.</li>
        <li><strong>Endorsed</strong> = of the heartbeats that got far enough to see a certificate, how many carried an extension signed by that validator&rsquo;s consensus key. The denominator excludes heartbeats that never completed TLS, because an endpoint that was down presented nothing to judge and counting it would report one outage twice.</li>
        <li><strong>TLS identity</strong> = the consensus-key check on the latest handshake: verified, expired (the right key, a lapsed window), mismatch, unverified, no TLS, or unreachable.</li>
        <li><strong>Serve rate by point</strong> is published per validator as well as network-wide. The four in-window points sit at different fractions of the retention window, so a validator that serves at the first point and not the last has pruned before it was allowed to, which is a different finding — and a different fix — from one that is poor throughout. The pooled rate cannot tell them apart.</li>
        <li><strong>Blob availability</strong> (per blob; <code>reconstructable</code> in the API) = at the latest in-window probe point, the union of row indices of validators that served their assigned rows correctly &mdash; the probe&rsquo;s outcome, not its class, which is why a row counts even where attestation would hold the probe out of the rate &mdash; is at least <code>OriginalRows</code> (4096 of 16384 for blob version 0). &ldquo;Rebuildable, not fully served&rdquo; (<code>degraded</code>) means enough rows but not every validator that was proven to owe the blob answered; a validator with no proof of storage cannot demote the verdict by staying quiet. A row that came back counts toward reconstruction either way, because the data was there: attestation decides blame, never availability. Grace and post points are never used for this verdict.</li>
        <li><strong>Throughput</strong> = bytes handed over per second during the download step alone, the median over the probes that came back HEALTHY. Fibre exists to be fast, and every other figure on this site would call a validator that serves everything in twenty seconds perfect. It is bytes over the download and not rows over the whole probe for two reasons. Assignments run from the 148-row floor to the 4,096-row ceiling, and the dial, handshake and identity check cost the same for both, so a whole-probe figure amortises that fixed cost over the big shard and not the small one and rises with stake by construction. And a row is as wide as its blob&rsquo;s square, so rows per second is not comparable across blobs; bytes are. The median and 95th percentile of the whole probe, dial to verified rows, are printed alongside, because that is what a client waits for and what an operator recognises from their own logs. <strong>No threshold is attached to any of it.</strong> This site watches from one place, so part of every millisecond is its own path, and calling a validator &ldquo;slow&rdquo; from one vantage would be the same mistake as calling one unreachable from one vantage. Failed probes are excluded: how long a failure took is not a service time.</li>
        <li>Every rate shows its numerator and denominator, and every serve rate carries a Wilson 95% <strong>upper bound on the fault rate</strong>, drawn around the obligation count rather than the probe count, because 3 of 3 is not 3000 of 3000. It is stated in that direction because that is the direction an accusation is made in.</li>
      </ul>

      <h2 id="gaps">Gaps</h2>
      <p>NOT_PROBED and PROBE_ERROR rows are the observer's own gaps: the slot elapsed while the observer was down, the probe policy sampled the blob out, or the probe itself failed. They are counted and shown, and never enter a rate. Observer run spans are recorded (<code>/api/v1/runs</code>), so downtime is rendered as a gap, not as zero.</p>
      <p>That holds per obligation, not only per probe, and it took a fix to make true. An obligation this site watched early and then lost sight of &mdash; the exact shape an outage here leaves in the record &mdash; used to keep its last good verdict and publish as <em>kept</em>, so the serve rate rose while nobody was watching. It is now <em>end unobserved</em>: outside the rate, counted beside it. The two directions are not symmetric, and the remaining bias belongs on this page rather than in a commit message. A fault is conclusive from one reading, because the shard was gone at that minute; a kept promise is a claim about a whole window, so it needs a reading near the end of one. While this site is blind, the obligations it can still judge are therefore enriched for faults. What its blindness cannot do is manufacture one: downtime here can only withhold credit from an operator, never accuse them, and the number of times it did is printed next to the rate.</p>
      <p>The observer also reports on itself. Each of its four processes keeps a status file, and <code>/api/v1/health</code> turns them into one verdict: which process is alive, when it last succeeded, how far the scanner is behind the chain, how much disk is left. The chip in the header is that verdict. Blocks the observer&rsquo;s own node could not serve are recorded as scan gaps and listed on the overview: a publication settled in one of them is unknown here, not counted as served or unserved.</p>

      <h2 id="sampling">Load policy and sampling</h2>
      <p>A probe transfers the validator's whole shard; there is no partial-row download in the protocol. To stay a small fraction of a validator's capacity, the prober enforces per-validator caps (requests per minute, bytes per hour and per day, scaled by assigned rows) and global caps. When the projected load for the next hour would exceed a cap, publications are sampled at probability <em>p</em> = cap / projected. The sample is deterministic and unpredictable: a blob is probed iff <code>H(promise_hash || day_secret) &lt; p · 2^64</code>, where <code>day_secret = HMAC(master, date)</code>. Every row this site stores, probed or sampled out, carries the probability it was decided at and a commitment to that day&rsquo;s secret (SHA-256 of the secret). Those commitments are published at <code>/api/v1/sampling</code>. Seven days after a day ends, its secret is published beside the commitment (the delay clears any retention window this site schedules, so the draw stays unpredictable while it matters), and from then on anyone can recompute the draw for every <code>MsgPayForFibre</code> settled that day and check which publications this site should have probed against which ones it did, from <code>/api/v1/probes</code>; <code>sentinel-recompute -sampling</code> does it from the daily export. A sampled-in blob gets its whole schedule; a sampled-out blob is recorded NOT_PROBED with the reason and <em>p</em>. Backoff only ever removes the download step, after three consecutive transport failures or rate limits from one validator and for twenty minutes; it never adds requests, and the slots it skips are recorded as <em>not probed</em>, which is a gap, never a verdict.</p>

      <h2 id="publishers">Publishers and fees</h2>
      <p>The Publishers page is the one part of this site that measures nothing. Every figure on it is a count of something the chain recorded: a <code>MsgPayForFibre</code> settling a promise, a <code>MsgPaymentPromiseTimeout</code> charging an abandoned one, a deposit to or withdrawal from escrow, and the escrow balance the chain holds for each account. The scanner reads these from the same blocks it reads publications from; nothing comes from a third-party index.</p>
      <ul>
        <li><strong>Fees.</strong> A settlement carries no amount in any chain event. The fee is recomputed from the promise&rsquo;s padded blob size with the module&rsquo;s own formula, <code>(650,000 + 45,000 × ⌈size / 256 KiB⌉)</code> gas at one utia per gas, which is exactly what the module charges. The formula is published on the page and in <code>/api/v1/market</code>, so any fee here can be checked from a blob size alone.</li>
        <li><strong>Who paid.</strong> The account charged is the one whose key signed the promise, whoever broadcast the transaction. A name next to an address is the operator&rsquo;s word, from a registry file this observer maintains; the chain has no name for an account, and the label&rsquo;s source is shown with it.</li>
        <li><strong>Timeouts are a floor.</strong> A promise that was signed and never settled leaves no trace on chain until someone submits its timeout, and the chain pays nobody for doing so. The count of timed-out promises is therefore the number somebody bothered to report, never the number abandoned. The settlement rate is stated over settlements plus reported timeouts and can only overstate how often publishers pay.</li>
        <li><strong>Timeouts enforced</strong> on a validator&rsquo;s page counts the timeouts its operator account submitted. It is matched on address bytes, so an operator that submits from another account is not credited; a zero says nothing.</li>
        <li><strong>Escrow</strong> is read by state query for every account already seen in a payment. The chain offers no query for every escrow, so an account that deposited and never published does not appear.</li>
        <li id="withdrawals"><strong>Withdrawals.</strong> A withdrawal request locks escrow until the withdrawal delay in force at the request has passed; the chain then pays it out in the first block whose time reaches that moment. Between the two, a settlement or timeout that finds the account&rsquo;s available balance short takes the difference out of its queued withdrawals, oldest first, shrinking one or removing it outright, and emits no event for it. The queue therefore cannot be rebuilt from events, and this site does not try: it reads it from chain state (<code>Withdrawals</code>) with each escrow balance, both at one height, and keeps the reads as history. What was taken from a queued withdrawal is shown as such. One that left the queue before it became payable was consumed by a settlement, with certainty. One that left after is called paid out only when exactly one payout of its last-seen amount landed between the two reads that bracket its departure; only those get a request-to-payout delay. Anything else is published as unattributed rather than guessed.</li>
        <li><strong>Not shown.</strong> Fees go to the fee collector and are distributed by stake through the distribution module; the chain records no per-validator share of Fibre income, so none is claimed. No publisher is scored: there is nothing in these records a publisher can do wrong.</li>
      </ul>

      <h2 id="evidence">What kind of claim each number is, and through which block</h2>
      <p>Every headline figure carries a small tag saying which of three kinds of evidence it rests on, because the three are different claims and a reader should never have to guess. <strong>chain</strong>: a count of something the chain recorded &mdash; publications, signatures, fees, registered endpoints &mdash; nothing here was measured by this site. <strong>verified</strong>: bytes this site fetched and checked against the on-chain commitment, or a certificate checked against the validator&rsquo;s consensus key &mdash; the serve rate, faults, obligations, endorsement. <strong>observed</strong>: what this site&rsquo;s own network saw from one location &mdash; reachability, throughput &mdash; which says nothing about any shard. On chain does not make a figure true of Fibre service, and a verified download is not a statement about anyone else&rsquo;s path to the endpoint. The same map is published under <code>evidence</code> in <code>/api/v1/meta</code>.</p>
      <p>Every snapshot also says <em>through which block</em> it was computed: <code>record_through</code> on <code>/api/v1/network</code>, <code>/api/v1/validators</code>, <code>/api/v1/market</code> and each validator&rsquo;s page carries the scanner&rsquo;s checkpoint height and its block time as they stood when the figures were taken, beside the chain tip the collector had last seen. <code>computed_at</code> says when; this says over which part of the record. The record is indexed by height and the clock is not, so this is the number to quote when checking a figure against the chain.</p>

      <h2 id="vantage">Vantage</h2>
      <p>All measurements on this site come from one vantage, named in the API (<code>/api/v1/meta</code>) and stamped on every probe row. A failed probe means this vantage could not fetch the rows at that time; it is not proof the validator is down. A successful probe is not proof of availability from elsewhere. Adding vantages multiplies load on validators, so a second one comes after the policy above has been published.</p>

      <h2 id="not">What this site does not do</h2>
      <ul>
        <li>It is not an availability proof and produces no slashing evidence; Fibre has no on-chain penalty for not serving.</li>
        <li>It does not extrapolate: rows not probed are not counted as served.</li>
        <li>It does not rank validators by anything other than the stored probe rows you can download from the API.</li>
      </ul>
    </div>
  );
}
