import { API_BASE } from "@/lib/api";

export const metadata = { title: "API · Muninn" };

const ROUTES: [string, string][] = [
  ["GET /v1/meta", "chain id, chain height, app version and whether Fibre is live on this chain, collector height, pinned celestia-app commit, protocol-params fingerprint, row counts, latest collector run with liveness, time of the newest measurement, vantage count and description."],
  ["GET /v1/network?window=24h|7d|30d|all", "registered endpoints, validators probed, reachability now and over the window, serve rate with its coverage and by-obligation rate, what the rate holds out and the excluded classes, attestation, verdict counts, probe count, gap count, publications and bytes, network-wide reconstructability."],
  ["GET /v1/validators?window=…", "one row per bonded validator (from the staking module), plus any with a registered endpoint or at least one probe: endpoint, reachability now and over the window, certificate endorsement rate, identity status, serve rate with its coverage, by-obligation rate, per-schedule-point breakdown, held-out counts and attestation, voting power, assigned rows and load band."],
  ["GET /v1/validators/{addr}", "addr is the 40-hex consensus address or celestiavalcons1…; adds 24h/7d/30d serve rates and the 50 most recent probes."],
  ["GET /v1/blobs?limit=&namespace=&before_height=", "newest publications first with probe counts and the reconstructability verdict."],
  ["GET /v1/blobs/{promise_hash}", "the publication, params in force, per-validator assignment, and every probe."],
  ["GET /v1/probes?validator=&blob=&since=&class=&limit=", "raw probe rows, newest first, at most 1000 per call."],
  ["GET /v1/runs?window=…", "observer run spans (start, last heartbeat, stop) used to render gaps."],
  ["GET /v1/sampling?window=…", "the load policy's admission record: one row per day-commitment with the probability publications were drawn at and how many were probed or sampled out, for the commit-and-reveal audit described in Methodology."],
];

export default function ApiDocs() {
  return (
    <div className="prose">
      <h1>API</h1>
      <p className="muted">Read-only JSON under <code>/v1/</code>, served at <code>{API_BASE}</code> for this dashboard. It is documented here so every number on the site can be traced to a response, but it is not offered as a public service yet: no rate limit, no uptime promise, and the routes may change. If you want the data, ask; the raw JSONL files and the SQLite database can be shared.</p>
      <div className="tablewrap">
        <table>
          <caption>Routes</caption>
          <thead><tr><th>route</th><th>returns</th></tr></thead>
          <tbody>{ROUTES.map(([r, d]) => <tr key={r}><td className="mono">{r}</td><td style={{ whiteSpace: "normal" }}>{d}</td></tr>)}</tbody>
        </table>
      </div>
      <h2>Conventions</h2>
      <ul>
        <li>Every rate is an object <code>{"{num, den, value}"}</code>; <code>value</code> is null when <code>den</code> is 0. Never a bare percentage.</li>
        <li>Timestamps are RFC 3339 UTC. Identifiers are lower-case hex; consensus addresses are the 20-byte address in hex, with the bech32 form where the registry knows it.</li>
        <li>Windows are fixed lookbacks from the server's clock; the response echoes <code>window.start</code> and <code>window.end</code>.</li>
        <li>Classes are the prober's classification strings (see Methodology). <code>NOT_PROBED</code> and <code>PROBE_ERROR</code> are gaps and are never in a rate. <code>UNATTESTED</code> (assigned rows, but the settled promise carries no verified signature from this validator, so nothing proves it ever stored the shard), <code>UNREACHABLE</code> (the observer could not complete a conversation with the endpoint; from one vantage that is not distinguishable from a problem on the observer's own path), <code>NOT_REGISTERED</code> (the validator had no Fibre host in x/valaddr at the time of the probe; jailing and unbonding remove a provider from the bonded list while the chain keeps the entry), <code>SHADOWED_SHARD</code> (the rows returned verify against the blob commitment but are not this promise's assignment, because DownloadShard is addressed by commitment alone and another promise over the same blob answers in its place) and <code>IDENTITY_EXPIRED</code> (the certificate is endorsed by the right consensus key but its signed validity window has lapsed — endpoint hygiene, not a retention failure) are recorded and shown but are also excluded from the serve rate, for the reason given with each.</li>
        <li>A new outcome, <code>SERVER_ERROR</code>, means the endpoint was reached, completed TLS and proved its identity, but answered the RPC with an application error — it is deliberately not treated as a reachability failure, since the validator was in fact reached and did answer. In-window it classifies as <code>FAULT</code>; in the grace phase it is <code>TOLERATED</code>; after the window it shows as <code>UNREACHABLE_POST_WINDOW</code>.</li>
        <li><code>serve_rate</code> is <code>HEALTHY / (HEALTHY + FAULT)</code> over assigned, attested probes in the in-window phase — the grace phase is outside the population, since a grace probe can only ever add HEALTHY; on <code>/v1/network</code> and per validator it comes with three companions. <code>serve_rate_coverage</code> is <code>(HEALTHY + FAULT) / all probes in that same population</code> — how much of the population actually produced a verdict, so a rate is never read as resting on more evidence than it has. <code>serve_rate_by_obligation</code> counts one observation per (validator, blob) rather than per probe, because the four in-window probes of one obligation are near copies of each other and only the by-obligation count is a population a confidence interval can honestly be drawn around. <code>serve_rate_held_out</code> is a map of classification to count for the probes the rate does not speak for, and <code>serve_rate_excluded_classes</code> is the fixed list of <code>{"{class, reason}"}</code> explaining, in the API's own words, why each such class (<code>UNATTESTED</code>, <code>UNREACHABLE</code>, <code>NOT_REGISTERED</code>, <code>SHADOWED_SHARD</code>, <code>IDENTITY_EXPIRED</code>, <code>NOT_PROBED</code>, <code>PROBE_ERROR</code>) is out.</li>
        <li><code>reachability_window</code> is the reachability heartbeat counted over the window rather than at its newest row: every registered endpoint is dialled every 10 minutes without downloading, so on <code>/v1/validators</code> it is <code>reachability_window</code> (heartbeats that completed TCP and TLS, over heartbeats sent), <code>identity_rate_window</code> (of those that saw a certificate, how many were endorsed by the validator&rsquo;s consensus key — the denominator excludes heartbeats that never reached TLS, since an endpoint that was down presented nothing to judge) and <code>last_unreachable_at</code>. On <code>/v1/network</code> it is the same over every heartbeat sent, beside <code>reachability</code>, which is a census of the endpoints as of their newest evidence. This is the only stability figure whose coverage does not depend on the chain proving an obligation.</li>
        <li><code>serve_latency_p50_ms</code>, <code>serve_latency_p95_ms</code> and <code>serve_latency_sample</code> are the whole probe &mdash; dial, TLS, <code>DownloadShard</code>, row verification against the commitment &mdash; over the probes that came back <code>HEALTHY</code>, on <code>/v1/network</code> and on each validator row. Failed probes are excluded: how long a failure took is not a service time. Per validator there is also <code>serve_rows_per_second</code>, and that is the one to compare between validators: assignments run from 148 rows to 4,096, so a validator carrying more rows takes longer for the same service, and sorting on duration names the busiest rather than the slowest. No threshold is attached to any of these.</li>
        <li><code>serve_rate_by_point</code> is the serve rate per schedule point, on <code>/v1/network</code> and on each validator row. The in-window points sit at different fractions of the retention window, so serving early and not late is a distinguishable finding from being poor throughout; the pooled rate is not.</li>
        <li><code>attestation</code> ({"{attested_probes, unattested_probes, unknown_probes, coverage, attested_blobs, unattested_blobs, unknown_blobs, blob_coverage}"}) discloses what the serve rate left out on proof-of-storage grounds. A validator only owes a blob it stored, and the sole on-chain proof of that is a verified signature on the settled promise; where it is missing a probe is <code>attested_probes</code> vs <code>unattested_probes</code>, and <code>coverage</code> is <code>attested / (attested + unattested)</code>. <code>unknown_probes</code> counts probes from records written before the observer verified signatures — their attestation is absent, not negative, so they stay inside the serve rate and outside <code>coverage</code>. The <code>_blobs</code> fields are the same three counts per (validator, blob) obligation rather than per probe, with <code>blob_coverage</code> over them; an obligation is visited at four schedule points, so the probe counts run about four times the blob counts, and it is the blob counts the site shows beside a named operator. An obligation counts as attested if any probe of it carries verified proof.</li>
        <li>A blob's own <code>reconstructable.status</code> (on <code>/v1/blobs</code> and <code>/v1/blobs/{"{promise_hash}"}</code>) is <code>yes</code>, <code>degraded</code>, <code>no</code>, <code>pending</code> (no in-window probe point is complete yet) or <code>unknown</code>; <code>pending</code> and <code>unknown</code> blobs are left out of the network rate.</li>
        <li>The network-wide <code>reconstructable</code> object on <code>/v1/network</code> is a different shape: <code>rate</code> is fully-served publications (status <code>yes</code>) over those with a verdict; <code>recoverable</code> additionally counts <code>degraded</code> publications, i.e. enough distinct rows came back to rebuild the blob whether or not every obliged validator answered — <code>rate</code> is the compliance question, <code>recoverable</code> is the availability one. <code>yes</code>, <code>degraded</code>, <code>no</code>, <code>pending</code> and <code>unknown</code> are the per-status counts behind both. Because this is computed per request rather than stored, it is bounded: <code>publications_in_window</code> is every publication the window holds, <code>publications_examined</code> is how many this request actually looked at (the newest ones first), and <code>sample_limit</code> is that bound (currently 2000). The two counts differ only when the window holds more than the limit.</li>
        <li><code>limit</code> outside 1..500 (blobs) or 1..1000 (probes) is a 400, never a silent default. Errors are <code>no-store</code>; only 200s are cacheable.</li>
        <li>Blob pagination is a two-part cursor: <code>before_height</code> plus <code>before_tx_index</code>, because one block can settle several publications.</li>
        <li>Each probe carries <code>clock_offset_ms</code> (the observer&apos;s clock against chain time) and, when it was retried after a transport timeout, <code>retry_first_outcome</code>.</li>
        <li>The underlying files are also plain: <code>publications.jsonl</code>, <code>measurements.jsonl</code> and <code>reachability.jsonl</code> are append-only records the store ingests; the SQLite file can be copied and queried directly.</li>
      </ul>
    </div>
  );
}
